blank_issues_enabled: false
contact_links:
  - name: Únase a nosotros en Discord, para cualquier pregunta o solicitud
    url: https://discord.io/VoxStudios
    about: No abra ningún problema que no sea para informar errores.
